#!/usr/bin/env bash
set -e -x

JOBS="${JOBS:-12}"
INPUT="${INPUT:-input}"
DATA="${DATA:-data}"
PLOT="${PLOT:-plot}"

case "$1" in
prepare_ceres_training)
	mkdir -p "$DATA"/samples/ceres_training
	parallel -j$JOBS -v bin/prepare_samples ceres "$INPUT"/ceres "$INPUT"/idd/synop "$INPUT"/idd/buoy "$INPUT"/landmask/ne_110m_land.nc both {}-01-01 {}-12-31 "$DATA"/samples/ceres_training/{} ::: {2009..2020}
	parallel -j1 -v bin/merge_samples "$DATA"/samples/ceres_training/{} "$DATA"/samples/ceres_training/{}.nc ::: {2009..2020}
	;;

train_ann)
	# Train the ANN.
	mkdir -p "$DATA"/ann
	bin/tf train "$DATA"/samples/ceres_training/ "$DATA"/ann/ceres.h5 "$DATA"/ann/history.nc
	;;

plot_training_history)
	bin/plot_training_history "$DATA"/ann/history.nc "$PLOT"/training_history.pdf
	;;

prepare_ceres)
	mkdir -p "$DATA"/samples/ceres/{2003..2014}
	parallel -j$JOBS -v bin/prepare_samples ceres "$INPUT"/ceres none none none none {}-01-01 {}-12-31 "$DATA"/samples/ceres/{} ::: {2003..2014}
	parallel -j1 -v bin/merge_samples "$DATA"/samples/ceres/{} "$DATA"/samples/ceres/{}.nc ::: {2003..2014}
	;;

prepare_historical)
	exp=historical
	for model in $(cat "$INPUT"/models_$exp); do
		if [ -e "$DATA"/samples/$exp/$model ]; then
			continue
		fi
		mkdir -p "$DATA"/samples/$exp/$model/{2003..2014}
		parallel -j$JOBS -v bin/prepare_samples cmip "$INPUT"/cmip6/$exp/day/by-model/$model none none none none {}-01-01 {}-12-31 "$DATA"/samples/$exp/$model/{} ::: {2003..2014}
		parallel -j1 -v bin/merge_samples "$DATA"/samples/$exp/$model/{} "$DATA"/samples/$exp/$model/{}.nc ::: {2003..2014}
	done
	model=EC-Earth3P
	if [ ! -e "$DATA"/samples/$exp/$model ]; then
		mkdir -p "$DATA"/samples/$exp/$model/{2003..2014}
		parallel -j$JOBS -v bin/prepare_samples cmip "$INPUT"/cmip6/hist-1950/day/by-model/$model none none none none {}-01-01 {}-12-31 "$DATA"/samples/$exp/$model/{} ::: {2003..2014}
		parallel -j1 -v bin/merge_samples "$DATA"/samples/$exp/$model/{} "$DATA"/samples/$exp/$model/{}.nc ::: {2003..2014}
	fi
	if [ -e "$INPUT"/merra2 ]; then
		model=MERRA-2
		if [ -e "$DATA"/samples/$exp/$model ]; then
			continue
		fi
		mkdir -p "$DATA"/samples/$exp/$model/{2003..2020}
		parallel -j$JOBS -v bin/prepare_samples merra2 "$INPUT"/merra2 none none none none {}-01-01 {}-12-31 "$DATA"/samples/$exp/$model/{} ::: {2003..2020}
		parallel -j1 -v bin/merge_samples "$DATA"/samples/$exp/$model/{} "$DATA"/samples/$exp/$model/{}.nc ::: {2003..2020}
	fi
	if [ -e "$INPUT"/era5 ]; then
		model=ERA5
		if [ -e "$DATA"/samples/$exp/$model ]; then
			continue
		fi
		mkdir -p "$DATA"/samples/$exp/$model/{2003..2020}
		parallel -j$JOBS -v bin/prepare_samples era5 "$INPUT"/era5 none none none none {}-01-01 {}-12-31 "$DATA"/samples/$exp/$model/{} ::: {2003..2020}
		parallel -j1 -v bin/merge_samples "$DATA"/samples/$exp/$model/{} "$DATA"/samples/$exp/$model/{}.nc ::: {2003..2020}
	fi
	if [ -e "$INPUT"/noresm2 ]; then
		model=NorESM2-LM
		if [ -e "$DATA"/samples/$exp/$model ]; then
			continue
		fi
		mkdir -p "$DATA"/samples/$exp/$model/{2003..2014}
		parallel -j$JOBS -v bin/prepare_samples noresm "$INPUT"/noresm2/$exp/day none none none none {}-01-01 {}-12-31 "$DATA"/samples/$exp/$model/{} ::: {2003..2014}
		parallel -j1 -v bin/merge_samples "$DATA"/samples/$exp/$model/{} "$DATA"/samples/$exp/$model/{}.nc ::: {2003..2014}
	fi
	;;

prepare_abrupt-4xCO2)
	exp=abrupt-4xCO2
	for model in $(cat "$INPUT"/models_$exp); do
		if [ -e "$DATA"/samples/$exp/$model ]; then
			continue
		fi
		mkdir -p "$DATA"/samples/$exp/$model/{1850..1949}
		parallel -j$JOBS -v prepare_samples cmip "$INPUT"/cmip6/$exp/day/by-model/$model none none none none {}-01-01 {}-12-31 "$DATA"/samples/$exp/$model/{} ::: {1850..1949}
		parallel -j1 -v bin/merge_samples "$DATA"/samples/$exp/$model/{} "$DATA"/samples_tf/$exp/$model/{}.nc ::: {1850..1949}
	done
	model=EC-Earth3P
	mkdir -p "$DATA"/samples/$exp/$model/{2003..2014}
	parallel -j$JOBS -v bin/prepare_samples cmip "$INPUT"/cmip6/hist-1950/day/by-model/$model none none none none {}-01-01 {}-12-31 "$DATA"/samples/$exp/$model/{} ::: {2003..2014}
	parallel -j1 -v bin/merge_samples "$DATA"/samples/$exp/$model/{} "$DATA"/samples/$exp/$model/{}.nc ::: {2003..2014}
	if [ -e "$INPUT"/noresm ]; then
		model=NorESM2-LM
		if [ -e "$DATA"/samples/$exp/$model ]; then
			continue
		fi
		mkdir -p "$DATA"/samples/$exp/noresm/{2003..2014}
		parallel -j$JOBS -v bin/prepare_samples noresm "$INPUT"/noresm/$exp/day none none none none {}-01-01 {}-12-31 "$DATA"/samples/$exp/$model/{} ::: {2003..2014}
		parallel -j1 -v bin/merge_samples "$DATA"/samples/$exp/$model/{} "$DATA"/samples/$exp/$model/{}.nc ::: {2003..2014}
	fi
	;;


label_ceres)
	mkdir -p "$DATA"/samples_tf/ceres/
	bin/tf apply "$DATA"/ann/ceres.h5 "$DATA"/samples/ceres 2003 2020 "$DATA"/samples_tf/ceres
	;;

label_historical)
	mkdir -p "$DATA"/samples_tf/ceres/
	for model in $(cat "$INPUT"/models_historical); do
		if [ ! -e "$DATA"/samples/historical/$model -o -e "$DATA"/samples_tf/historical/$model ]; then
			continue
		fi
		mkdir -p "$DATA"/samples_tf/historical/$model
		bin/tf apply "$DATA"/ann/ceres.h5 "$DATA"/samples/historical/$model 2003 2014 "$DATA"/samples_tf/historical/$model
	done
	;;

label_abrupt-4xCO2)
	for model in $(cat "$INPUT"/models_abrupt-4xCO2); do
		if [ ! -e "$DATA"/samples/historical/$model -o -e "$DATA"/samples_tf/historical/$model ]; then
			continue
		fi
		mkdir -p "$DATA"/samples_tf/abrupt-4xCO2/$model
		bin/tf apply "$DATA"/ann/ceres.h5 "$DATA"/samples/abrupt-4xCO2/$model 1850 1949 "$DATA"/samples_tf/abrupt-4xCO2/$model
	done
	;;

calc_dtau_pct)
	bin/calc_dtau_pct "$DATA"/samples_tf/ceres "$INPUT"/ceres "$DATA"/dtau_pct/dtau_pct.nc
	;;

plot_dtau_pct)
	bin/plot_dtau_pct "$DATA"/dtau_pct/dtau_pct.nc "$PLOT"/dtau_pct.pdf
	;;

calc_geo_cto_historical)
	mkdir -p "$DATA"/geo_cto/historical/all
	if [ ! -e "$DATA"/geo_cto/historical/all/CERES.nc ]; then
		bin/calc_geo_cto "$DATA"/samples_tf/ceres "$INPUT"/tas/historical/CERES.nc "$DATA"/geo_cto/historical/all/CERES.nc
	fi
	for model in $(cat "$INPUT"/models_historical); do
		if [ ! -e "$DATA"/samples_tf/historical/$model -o -e "$DATA"/geo_cto/historical/all/$model.nc ]; then
			continue
		fi
		bin/calc_geo_cto "$DATA"/samples_tf/historical/$model "$INPUT"/tas/historical/$model.nc "$DATA"/geo_cto/historical/all/$model.nc
	done
	mkdir -p "$DATA"/geo_cto/historical/part_{1,2}/
	for model in $(cat "$INPUT"/models_historical_part_1); do
		if [ ! -e "$DATA"/geo_cto/historical/all/$model.nc ]; then
			continue
		fi
		cp "$DATA"/geo_cto/historical/all/$model.nc "$DATA"/geo_cto/historical/part_1/
	done
	for model in $(cat "$INPUT"/models_historical_part_2); do
		if [ ! -e "$DATA"/geo_cto/historical/all/$model.nc ]; then
			continue
		fi
		cp "$DATA"/geo_cto/historical/all/$model.nc "$DATA"/geo_cto/historical/part_2/
	done
	;;

calc_geo_cto_abrupt-4xCO2)
	mkdir -p "$DATA"/geo_cto/abrupt-4xCO2/all
	for model in $(cat "$INPUT"/models_abrupt-4xCO2); do
		if [ ! -e "$DATA"/samples_tf/historical/$model -o -e "$DATA"/geo_cto/historical/all/$model.nc ]; then
			continue
		fi
		bin/calc_geo_cto "$DATA"/samples_tf/abrupt-4xCO2/$model "$INPUT"/tas/abrupt-4xCO2/$model.nc "$DATA"/geo_cto/abrupt-4xCO2/all/$model.nc
	done
	mkdir -p "$DATA"/geo_cto/abrupt-4xCO2/part_{1,2}/
	for model in $(cat "$INPUT"/models_abrupt-4xCO2_part_1); do
		if [ ! -e "$DATA"/geo_cto/historical/all/$model.nc ]; then
			continue
		fi
		cp "$DATA"/geo_cto/abrupt-4xCO2/all/$model.nc "$DATA"/geo_cto/abrupt-4xCO2/part_1/
	done
	for model in $(cat "$INPUT"/models_abrupt-4xCO2_part_2); do
		if [ ! -e "$DATA"/geo_cto/historical/all/$model.nc ]; then
			continue
		fi
		cp "$DATA"/geo_cto/abrupt-4xCO2/all/$model.nc "$DATA"/geo_cto/abrupt-4xCO2/part_2/
	done
	;;

plot_geo_cto_historical)
	bin/plot_geo_cto 0 true "$DATA"/geo_cto/historical/part_1 "$INPUT"/ecs/ecs.csv "$PLOT"/geo_cto_historical_1.pdf
	bin/plot_geo_cto 0 true "$DATA"/geo_cto/historical/part_2 "$INPUT"/ecs/ecs.csv "$PLOT"/geo_cto_historical_2.pdf
	;;

plot_geo_cto_abrupt-4xCO2)
	bin/plot_geo_cto 0 true "$DATA"/geo_cto/abrupt-4xCO2/part_1 "$INPUT"/ecs/ecs.csv "$PLOT"/geo_cto_abrupt-4xCO2_1.pdf
	bin/plot_geo_cto 0 true "$DATA"/geo_cto/abrupt-4xCO2/part_2 "$INPUT"/ecs/ecs.csv "$PLOT"/geo_cto_abrupt-4xCO2_2.pdf
	;;

plot_geo_cto_rmse)
	for var in ecs tcr cld; do
		bin/plot_geo_cto_rmse $var "$DATA"/geo_cto/historical/all "$INPUT"/ecs/ecs.csv "$PLOT"/geo_cto_rmse_${var}.pdf
	done
	;;

calc_cto_historical)
	bin/calc_cto "$DATA"/samples_tf/historical "$INPUT"/tas/historical "$DATA"/cto/historical/cto.nc
	;;

calc_cto_abrupt-4xCO2)
	bin/calc_cto "$DATA"/samples_tf/abrupt-4xCO2 "$INPUT"/tas/abrupt-4xCO2 "$DATA"/cto/abrupt-4xCO2/cto.nc
	;;

plot_cto_historical)
	bin/plot_cto ecs 0 relative false "$DATA"/cto/historical/cto.nc "$INPUT"/ecs/ecs.csv "$PLOT"/cto_historical.pdf 'CMIP6 historical (2003-2014) and reanalyses (2003-2020) relative to CERES (2003-2020)'
	;;

plot_cto_abrupt-4xCO2)
	bin/plot_cto ecs 1-tas absolute false "$DATA"/cto/abrupt-4xCO2/cto.nc "$INPUT"/ecs/ecs.csv "$PLOT"/cto_abrupt-4xCO2.pdf 'CMIP abrupt-4xCO2 (1850-1949) and CERES (2003-2020)'
	;;

calc_cto_esc)
	bin/calc_cto_ecs "$DATA"/cto/abrupt-4xCO2/cto.nc "$INPUT"/ecs/ecs.csv "$DATA"/cto_ecs/cto_ecs.nc
	;;

plot_cto_ecs)
	bin/plot_cto_ecs ecs "$DATA"/cto/abrupt-4xCO2/cto.nc "$DATA"/cto_ecs/cto_ecs.nc "$PLOT"/cto_ecs.pdf
	;;

plot_tf_scheme)
	bin/plot_tf_scheme "$PLOT"/tf_scheme.pdf
	;;

*)
	printf "%s: Unknown command\n" "$1" >&2
esac
